apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-promotion-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-promotion
  template:
    metadata:
      labels:
        app: event-promotion
    spec:
      containers:
      - name: event-promotion-container
        # Updated to use your classmate's registry URL
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/event-promotion-website:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-storage
          mountPath: /var/www/html/uploads
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: pvc-uploads